### ISSUE TITLE
Any plan to support cli option for http/https proxy?

### ISSUE THREAD

**Issue by atztogo** [aiidateam/aiida-pseudo#108]
I am looking for a way to install SSSP behind http/https proxy, and I could not find it. So I hard-coded http-proxy and it seems working. For other people in my institute, I want to have a cli option to provide http/https proxy information. Do you already have such a plan?

**Comment by sphuber** [comment]
Hi @atztogo we have been working on this in #94 . At least I think that should fix the problem you are describing. I think we almost arrived at the ideal solution, both in terms of flexibility/ease of use/ but while keeping things consistent. The idea is to add the option `--download-only` to the `aiida-pseudo install sssp/pseudo-dojo` commands. This will produce a single file on disk (containing all the files it downloaded). The commands than also get the option `--from-download` that can consume such an archive. So you can download the archive on a non-blocked computer, get it to the computer behind a proxy and then use `--from-download` to install from file instead of downloading it.

Would this work, or are you describing a different issue? And if so, could you share your solution perhaps?

**Comment by atztogo** [comment]
Yes, it solves the problem. Thanks @sphuber!
