### ISSUE TITLE
Problem with "aiida-pseudo install sssp"

### ISSUE THREAD

**Issue by SangbumYi** [aiidateam/aiida-pseudo#131]
The command "aiida-pseudo install sssp" gives the error message 

Critical: HTTPSConnectionPool(host='legacy-archive.materialscloud.org', port=443): Max retries exceeded with url: /file/2018.0001/v4//SSSP_1.1_PBE_efficiency.tar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa80332f950>: Failed to establish a new connection: [Errno 110] Connection timed out'))

This issue was already reported in #59, but it seems the legacy repository hasn't been updated yet.

Could you please let me know how to fix?

**Comment by sphuber** [comment]
This should have been fixed with https://github.com/aiidateam/aiida-pseudo/commit/707a16c189caaa9b5ae4ec19c6f7dad3164ad171 which was released with `v0.7.0`. What version do you have installed? Run `pip freeze  | grep aiida-pseudo`. If it is and older version, upgrade it with `pip install --upgrade aiida-pseudo`.

**Comment by SangbumYi** [comment]
Hi sphuber,
I greatly appreciate your help.
It seems I was running aiida-pseudo  v0.6.2, which was the default version installed on Quantum Mobile v21.06.04.

The issue has been resolved by upgrading aiida-pseudo, as per your advice.

Thank you
