### ISSUE TITLE
Storing the units for the recommended cuttoffs

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-pseudo#47]
Recently when I was trying to use aiida-pseudo with https://github.com/aiidateam/aiida-quantumespresso-epfl, it turned out I needed to convert the units from those I'd previously used with aiida-sssp, and also @flavianojs got into some similar issues with units.

So it would be good if the units were stored as part of this data, and in some way e.g. aiida-quantumespresso could check this (converting if necessary or raising an error if it can't)
(alternatively it could directly store the conversion factor to hartree or eV)

cc also @mbercx

**Comment by mbercx** [comment]
Just for reference:

* @chrisjsewell was using the old protocol methods in https://github.com/aiidateam/aiida-quantumespresso-epfl, but (correct me if I'm wrong) manually getting the recommended cutoffs using the `get_recommended_cutoffs()` method and passing them straight as inputs. This means the cutoffs were expressed in eV and he quickly ran into memory issues. 😅 
* @flavianojs had installed the SSSP pseudos with a previous version of `aiida-pseudo` (pre-v0.4.0, I'm assuming), and was now using the latest `develop` branch of `aiida-quantumespresso`, which expected the recommended cutoffs to be expressed in eV. So in his case the cutoffs were reduced by a factor 13.6, which Quantum ESPRESSO did not like.

I suppose we can:

* add the units in the dictionary stored in the `'_cutoffs'` extra of the group.
* add the units as a third item in the tuple returned by `get_recommended_cutoffs` method. This wouldn't be backwards compatible though, e.g. this line in `aiida-quantumespresso` would fail:

```Python
cutoff_wfc, cutoff_rho = pseudo_family.get_recommended_cutoffs(structure=structure)
```

**Comment by sphuber** [comment]
I would say we add the unit as an extra to the group (not necessarily within `_cutoffs`, could be something else) and expose additional method `get_recommended_cutoff_unit`. The reason we hadn't done this yet was because a) this project is in beta phase :) and b) we needed to come up with a "standard" of storing units in node attributes/extras. It is kind of surprising that in all these years of AiiDA we don't actually have this. We have been relying on using the same unit as much as possible in all attributes, but I think it really is unavoidable that we should start to think how to include units with values. Don't think this will be solved anytime soon, so maybe we can start here with a suggestions. Is there one standard that defines how each unit should be "named", i.e. electronvolt should always be `eV` or `ev` or `electronvolt` or what have you. If can find that standard then we can, for now, just turn that into an enum and store the relevant value in the extras for each group

**Comment by chrisjsewell** [comment]
We may not need such complexity here, but FYI a package that I have found useful before, for dealing with units is https://pint.readthedocs.io

**Comment by mbercx** [comment]
> We may not need such complexity here, but FYI a package that I have found useful before for dealing with units is https://pint.readthedocs.io

Their logo is a beer... We _must_ use this package. 😁
