### ISSUE TITLE
Move `aiida-pseudo show` to `aiida-pseudo family show`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-pseudo#56]
There will be more commands in the near future that operate on a specific family instance and so it would make more sense to group them in the subcommand `aiida-pseudo family`

**Comment by Angmar1989** [comment]
Concerning the aiida-pseudo family, I have some problems during learning to use the aiida, the command "aiida-pseudo install SSSP" always fails at the third step"unpacking archives and parsing pseudos...", I downloaded the pseudo library, and extract the tar file, and with the command"verdi data upf uploadfamily path/to/folder name_of_the_family "some description for your convenience""  to create a pseudo family, however, the command "aiida-psrudo list" end up with the result"no pseudo potential families have been installed yet", why is that? I have been looking for solutions for a few days, little information could be abtained, since no instruction for install pseudo family offline at all. Could you please tell me what I missed to install the pseudo family? Thanks very much.

**Comment by sphuber** [comment]
@Angmar1989 I have split your question off to a separate issue #59 I will continue the discussion there

**Comment by Angmar1989** [comment]
> @Angmar1989 I have split your question off to a separate issue #59 I will continue the discussion there

Thanks!
