### ISSUE TITLE
`RecommendedCutoffMixin`: change`set_cutoffs` API to only set one stringency 

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-pseudo#68]
Currently the behaviour of  the `set_cutoffs` and `get_cutoffs` methods of the `RecommendedCutoffMixin` class is different. The first sets the cutoffs for all stringencies along with a default stringency, and the second only retrieves the cutoffs for a specified stringency. This can be somewhat confusing for the user, and means that the user cannot easily set the cutoffs for a single stringency.

It would be more intuitive to change the `set_cutoffs` method to only set the cutoffs for a single stringency. This way changing a single stringency is straightforward, and the user can simply call the method in a loop to set multiple stringencies. In addition, we can add the `set_default_stringency` method so the user can still specify a default.

**Comment by mbercx** [comment]
Some more design questions:

* Since we now don't specify the `default_stringency` when setting the cutoffs, are we ok with the user being able to specify the cutoffs but _not_ a `default_stringency`? If the user has only specified one set of cutoffs, maybe it's weird to then also ask her/him to specify a default stringency?
* Similarly for the units: If we set _all_ cutoffs at once with a unit, it's fine that we only have one unit stored in the extras. However, if we allow the user to set one stringency at a time, it's possible they might want to assign different units to the different stringencies. Should we then make the `'_cutoffs_unit'` extra a dictionary that contains the units for each stringency?

**Comment by sphuber** [comment]
> Since we now don't specify the `default_stringency` when setting the cutoffs, are we ok with the user being able to specify the cutoffs but _not_ a `default_stringency`? If the user has only specified one set of cutoffs, maybe it's weird to then also ask her/him to specify a default stringency?

I think we should definitely add a `set_default_stringency` method, which raises if the stringency does not exist. Then we can add a check in `set_cutoffs` after having set the cutoffs, that if only 1 stringency exists, that is made the default as well. In that case, there will always be a default stringency defined as soon as 1 stringency has been defined at some point.

> Similarly for the units: If we set _all_ cutoffs at once with a unit, it's fine that we only have one unit stored in the extras. However, if we allow the user to set one stringency at a time, it's possible they might want to assign different units to the different stringencies. Should we then make the `'_cutoffs_unit'` extra a dictionary that contains the units for each stringency?

The original idea was to only ever support a single unit for all stringencies. This is also why `set_cutoffs` also set multiple stringencies and there was no method to define a single stringency. Now that this feature is added, we are forced indeed to make the units a dictionary mapped onto the stringencies. Think that is fine to do, since we already decided that we would want to have the ability to define a single stringency at a time.
